package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CientGroup generated by hbm2java
 */
public class CientGroup implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private Set clients = new HashSet(0);

	public CientGroup() {
	}

	public CientGroup(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public CientGroup(String id, String name, String description, Set clients) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.clients = clients;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

}
