package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClientHistory generated by hbm2java
 */
public class ClientHistory implements java.io.Serializable {

	private ClientHistoryId id;

	public ClientHistory() {
	}

	public ClientHistory(ClientHistoryId id) {
		this.id = id;
	}

	public ClientHistoryId getId() {
		return this.id;
	}

	public void setId(ClientHistoryId id) {
		this.id = id;
	}

}
