package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private String emloyeeId;
	private String persCode;
	private String name;
	private String lastName;
	private String password;
	private String mail;
	private String id;

	public Employee() {
	}

	public Employee(String emloyeeId, String persCode, String name, String lastName, String password, String mail,
			String id) {
		this.emloyeeId = emloyeeId;
		this.persCode = persCode;
		this.name = name;
		this.lastName = lastName;
		this.password = password;
		this.mail = mail;
		this.id = id;
	}

	public String getEmloyeeId() {
		return this.emloyeeId;
	}

	public void setEmloyeeId(String emloyeeId) {
		this.emloyeeId = emloyeeId;
	}

	public String getPersCode() {
		return this.persCode;
	}

	public void setPersCode(String persCode) {
		this.persCode = persCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
