package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * LoanOfferHistory generated by hbm2java
 */
public class LoanOfferHistory implements java.io.Serializable {

	private String changeId;
	private String offerId;
	private String employeeId;
	private String comment;
	private String date;

	public LoanOfferHistory() {
	}

	public LoanOfferHistory(String changeId, String offerId, String employeeId, String comment, String date) {
		this.changeId = changeId;
		this.offerId = offerId;
		this.employeeId = employeeId;
		this.comment = comment;
		this.date = date;
	}

	public String getChangeId() {
		return this.changeId;
	}

	public void setChangeId(String changeId) {
		this.changeId = changeId;
	}

	public String getOfferId() {
		return this.offerId;
	}

	public void setOfferId(String offerId) {
		this.offerId = offerId;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
