package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * Loan generated by hbm2java
 */
public class Loan implements java.io.Serializable {

	private String id;
	private String dueDate;
	private String baseDueDate;
	private String apr;
	private String debt;
	private int clientId;
	private String employeeId;
	private String status;
	private String offerId;
	private String postponeRequestId;

	public Loan() {
	}

	public Loan(String id, String dueDate, String baseDueDate, String apr, String debt, int clientId, String status,
			String offerId) {
		this.id = id;
		this.dueDate = dueDate;
		this.baseDueDate = baseDueDate;
		this.apr = apr;
		this.debt = debt;
		this.clientId = clientId;
		this.status = status;
		this.offerId = offerId;
	}

	public Loan(String id, String dueDate, String baseDueDate, String apr, String debt, int clientId,
			String employeeId, String status, String offerId, String postponeRequestId) {
		this.id = id;
		this.dueDate = dueDate;
		this.baseDueDate = baseDueDate;
		this.apr = apr;
		this.debt = debt;
		this.clientId = clientId;
		this.employeeId = employeeId;
		this.status = status;
		this.offerId = offerId;
		this.postponeRequestId = postponeRequestId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(String dueDate) {
		this.dueDate = dueDate;
	}

	public String getBaseDueDate() {
		return this.baseDueDate;
	}

	public void setBaseDueDate(String baseDueDate) {
		this.baseDueDate = baseDueDate;
	}

	public String getApr() {
		return this.apr;
	}

	public void setApr(String apr) {
		this.apr = apr;
	}

	public String getDebt() {
		return this.debt;
	}

	public void setDebt(String debt) {
		this.debt = debt;
	}

	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getOfferId() {
		return this.offerId;
	}

	public void setOfferId(String offerId) {
		this.offerId = offerId;
	}

	public String getPostponeRequestId() {
		return this.postponeRequestId;
	}

	public void setPostponeRequestId(String postponeRequestId) {
		this.postponeRequestId = postponeRequestId;
	}

}
