package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * LoanHistoryId generated by hbm2java
 */
public class LoanHistoryId implements java.io.Serializable {

	private String date;
	private String event;
	private String loanId;

	public LoanHistoryId() {
	}

	public LoanHistoryId(String date, String event, String loanId) {
		this.date = date;
		this.event = event;
		this.loanId = loanId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	public String getLoanId() {
		return this.loanId;
	}

	public void setLoanId(String loanId) {
		this.loanId = loanId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoanHistoryId))
			return false;
		LoanHistoryId castOther = (LoanHistoryId) other;

		return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this
				.getDate().equals(castOther.getDate())))
				&& ((this.getEvent() == castOther.getEvent()) || (this.getEvent() != null
						&& castOther.getEvent() != null && this.getEvent().equals(castOther.getEvent())))
				&& ((this.getLoanId() == castOther.getLoanId()) || (this.getLoanId() != null
						&& castOther.getLoanId() != null && this.getLoanId().equals(castOther.getLoanId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getEvent() == null ? 0 : this.getEvent().hashCode());
		result = 37 * result + (getLoanId() == null ? 0 : this.getLoanId().hashCode());
		return result;
	}

}
