package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * LoanOffer generated by hbm2java
 */
public class LoanOffer implements java.io.Serializable {

	private String offerId;
	private String sum;
	private String period;
	private String apr;
	private String ratingBonus;
	private String ratingDrop;
	private String statusId;
	private String clientGroupId;

	public LoanOffer() {
	}

	public LoanOffer(String offerId, String sum, String period, String apr, String ratingBonus, String ratingDrop,
			String statusId, String clientGroupId) {
		this.offerId = offerId;
		this.sum = sum;
		this.period = period;
		this.apr = apr;
		this.ratingBonus = ratingBonus;
		this.ratingDrop = ratingDrop;
		this.statusId = statusId;
		this.clientGroupId = clientGroupId;
	}

	public String getOfferId() {
		return this.offerId;
	}

	public void setOfferId(String offerId) {
		this.offerId = offerId;
	}

	public String getSum() {
		return this.sum;
	}

	public void setSum(String sum) {
		this.sum = sum;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getApr() {
		return this.apr;
	}

	public void setApr(String apr) {
		this.apr = apr;
	}

	public String getRatingBonus() {
		return this.ratingBonus;
	}

	public void setRatingBonus(String ratingBonus) {
		this.ratingBonus = ratingBonus;
	}

	public String getRatingDrop() {
		return this.ratingDrop;
	}

	public void setRatingDrop(String ratingDrop) {
		this.ratingDrop = ratingDrop;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public String getClientGroupId() {
		return this.clientGroupId;
	}

	public void setClientGroupId(String clientGroupId) {
		this.clientGroupId = clientGroupId;
	}

}
