package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * LoanHistory generated by hbm2java
 */
public class LoanHistory implements java.io.Serializable {

	private LoanHistoryId id;

	public LoanHistory() {
	}

	public LoanHistory(LoanHistoryId id) {
		this.id = id;
	}

	public LoanHistoryId getId() {
		return this.id;
	}

	public void setId(LoanHistoryId id) {
		this.id = id;
	}

}
