package com.loansystem.model;

// default package
// Generated Nov 13, 2011 9:49:21 PM by Hibernate Tools 3.4.0.CR1

/**
 * PostponeRequest generated by hbm2java
 */
public class PostponeRequest implements java.io.Serializable {

	private String id;
	private String statusId;
	private String date;
	private String employeeId;
	private String comment;

	public PostponeRequest() {
	}

	public PostponeRequest(String id, String statusId, String date) {
		this.id = id;
		this.statusId = statusId;
		this.date = date;
	}

	public PostponeRequest(String id, String statusId, String date, String employeeId, String comment) {
		this.id = id;
		this.statusId = statusId;
		this.date = date;
		this.employeeId = employeeId;
		this.comment = comment;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
